// 共通エラーコード
export const ERROR_CODES = {
  // 汎用エラー
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // 認証・認可エラー
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // データ操作エラー
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_OPERATION: 'INVALID_OPERATION',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // General Cost関連エラー
  GENERAL_COST: {
    DUPLICATE_CODE: 'GENERAL_COST_DUPLICATE_CODE',
    INVALID_CODE: 'GENERAL_COST_INVALID_CODE',
    FETCH_ERROR: 'GENERAL_COST_FETCH_ERROR',
    CREATE_ERROR: 'GENERAL_COST_CREATE_ERROR',
    UPDATE_ERROR: 'GENERAL_COST_UPDATE_ERROR',
    DELETE_ERROR: 'GENERAL_COST_DELETE_ERROR',
    UPDATE_NAME_ERROR: 'GENERAL_COST_UPDATE_NAME_ERROR',
  },

  // Business Cost関連エラー
  BUSINESS_COST: {
    FETCH_ERROR: 'BUSINESS_COST_FETCH_ERROR',
    CREATE_ERROR: 'BUSINESS_COST_CREATE_ERROR',
    UPDATE_ERROR: 'BUSINESS_COST_UPDATE_ERROR',
    DELETE_ERROR: 'BUSINESS_COST_DELETE_ERROR',
  },

  // Cost Version関連エラー
  COST_VERSION: {
    DUPLICATE_ID: 'COST_VERSION_DUPLICATE_ID',
    INVALID_ID: 'COST_VERSION_INVALID_ID',
    NOT_FOUND: 'COST_VERSION_NOT_FOUND',
    FETCH_ERROR: 'COST_VERSION_FETCH_ERROR',
    CREATE_ERROR: 'COST_VERSION_CREATE_ERROR',
    UPDATE_ERROR: 'COST_VERSION_UPDATE_ERROR',
    DELETE_ERROR: 'COST_VERSION_DELETE_ERROR',
    DUPLICATE_ERROR: 'COST_VERSION_DUPLICATE_ERROR',
    DEFAULT_UPDATE_ERROR: 'COST_VERSION_DEFAULT_UPDATE_ERROR',
    VALIDATION_ERROR: 'COST_VERSION_VALIDATION_ERROR',
    BUSINESS_ERROR: 'COST_VERSION_BUSINESS_ERROR',
  },

  // 外部API関連エラー
  EXTERNAL_API: {
    CONNECTION_ERROR: 'EXTERNAL_API_CONNECTION_ERROR',
    TIMEOUT: 'EXTERNAL_API_TIMEOUT',
    RATE_LIMIT: 'EXTERNAL_API_RATE_LIMIT',
    INVALID_RESPONSE: 'EXTERNAL_API_INVALID_RESPONSE',
  },
} as const;

// エラーコードの型
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type GeneralCostErrorCode = (typeof ERROR_CODES.GENERAL_COST)[keyof typeof ERROR_CODES.GENERAL_COST];
export type BusinessCostErrorCode = (typeof ERROR_CODES.BUSINESS_COST)[keyof typeof ERROR_CODES.BUSINESS_COST];
export type ExternalApiErrorCode = (typeof ERROR_CODES.EXTERNAL_API)[keyof typeof ERROR_CODES.EXTERNAL_API];
